# Generated by Django 3.2.3 on 2021-05-29 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whizapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter',
            new_name='user',
        ),
    ]
