# Generated by Django 3.2.3 on 2021-05-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizapp', '0002_rename_commenter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
