# Generated by Django 3.2.3 on 2021-05-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizapp', '0003_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
