# Generated by Django 3.2.3 on 2021-05-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whizapp', '0007_remove_commentreply_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
