# Generated by Django 3.2.3 on 2021-05-30 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('whizapp', '0009_commentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
